POST http://localhost:3000/sellers/ HTTP/1.1
content-type: application/json

{"name":"Hust the seller"}
###
POST http://localhost:3000/clients HTTP/1.1
content-type: application/json

{"name":"posted client"}

###
GET  http://localhost:3000/products/6194069ae6ad9fd6c5af2b29 HTTP/1.1

###
PATCH http://localhost:3000/sellers/618b788cd7d24a0cc5a9dd7f HTTP/1.1
content-type: application/json

{"name":"patched client of mongo"}

###
POST http://localhost:3000/sellers/618b788cd7d24a0cc5a9dd7f HTTP/1.1
content-type: application/json

{"productHeader":"lool","price": "45"}

###
GET http://localhost:3000/products/search?sellerId=619bb08596a169e83648f63d HTTP/1.1
###
GET http://localhost:3000/sellers/618b788cd7d24a0cc5a9dd7f HTTP/1.1
###
GET http://localhost:3000/products/search?sellerId=618b788cd7d24a0cc5a9dd7f HTTP/1.1

###
POST http://localhost:3000/clients/619cf04ef06d50d306d1735f/buyproduct?productId=619bb14896a169e83648f64f